const assert=require('node:assert/strict'),fs=require('node:fs');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});const errors=[],passed=[];let calls=0;
 const context=await browser.newContext({permissions:['clipboard-read','clipboard-write']});
 await context.route('https://company.example/**',r=>r.fulfill({body:'Mock company Agent landing page',contentType:'text/html'}));
 await context.route('https://api.github.com/**',r=>r.fulfill({json:{workflow_runs:[]}}));
 const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));
 p.on('request',r=>{if(/\/analyze|generativelanguage|api.openai/.test(r.url()))calls++;});
 await p.addInitScript(()=>localStorage.setItem('regwatch_ai_endpoint','https://old-worker.example/analyze'));
 try{
 await p.goto('http://127.0.0.1:8765/Financial-tracker/ui-v2/');await p.locator('#priority-list .priority-summary').first().click();assert.equal(await p.locator('#detail-content .gemini-button').count(),1);
 await p.locator('.gemini-button').first().click();await p.locator('#gemini-preview').waitFor();assert.match(await p.locator('[data-message]').innerText(),/주소가 아직 설정되지 않았습니다/);let prompt=await p.locator('#gemini-prompt').inputValue();assert.ok(prompt.length>1000);assert.equal((await p.evaluate(()=>navigator.clipboard.readText())).replace(/\r\n/g,'\n'),prompt);await p.locator('#gemini-preview [data-close]').first().click();await p.locator('#close-detail').click();passed.push('real clipboard, missing Agent URL and detail controls');
 await p.locator('#scope-select').selectOption('aml');await p.locator('#regulation-list [data-action="detail"]').first().click();await p.locator('.gemini-preview-toggle summary').click();await p.getByText('분석 Prompt 미리보기',{exact:true}).click();assert.match(await p.locator('#gemini-prompt').inputValue(),/현재 선택된 업무 관점:\nAML/);await p.locator('#gemini-preview [data-close]').first().click();await p.locator('#close-detail').click();await p.locator('#scope-select').selectOption('all');passed.push('detail preview and current AML scope');
 await p.locator('#priority-list .priority-summary').first().click();await p.evaluate(()=>RegWatchGemini.setAgentUrl('https://company.example/agent'));await p.waitForTimeout(1500);
 const tabPromise=context.waitForEvent('page');await p.locator('.gemini-button').first().click();const tab=await tabPromise;await tab.waitForURL('https://company.example/agent');assert.equal(await tab.evaluate(()=>window.opener),null);await p.locator('.gemini-button').first().click();assert.equal(context.pages().length,2);await tab.close();passed.push('real popup to intercepted mock company URL, opener removed, double click suppressed');
 await p.waitForTimeout(1600);await p.evaluate(()=>{window.open=()=>null;});await p.locator('.gemini-button').first().click();await p.locator('#gemini-preview').waitFor();assert.match(await p.locator('[data-message]').innerText(),/차단되었습니다/);assert.equal(await p.locator('[data-open]').getAttribute('href'),'https://company.example/agent');await p.locator('#gemini-preview [data-close]').first().click();passed.push('popup blocked manual link');
 await p.waitForTimeout(1600);await p.evaluate(()=>{Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async()=>{throw Error('denied');}}});document.execCommand=()=>false;});await p.locator('.gemini-button').first().click();await p.locator('#gemini-preview').waitFor();assert.match(await p.locator('[data-message]').innerText(),/직접 복사/);assert.ok((await p.locator('#gemini-prompt').inputValue()).length>1000);await p.locator('#gemini-preview [data-close]').first().click();passed.push('clipboard denied and execCommand denied manual text fallback');
 assert.equal(await p.evaluate(async()=>{document.execCommand=()=>true;return RegWatchGemini.copyPromptToClipboard('fallback');}),true);passed.push('legacy copy fallback');
 await p.evaluate(()=>RegWatchGemini.renderGeminiPromptPreview(RegWatchGemini.buildGeminiRegulationPrompt({title:'<img src=x onerror="window.xss=1">',content:'<script>window.xss=1</script>',url:'javascript:alert(1)'})));assert.equal(await p.locator('#gemini-preview img, #gemini-preview script').count(),0);assert.equal(await p.evaluate(()=>window.xss),undefined);passed.push('preview XSS protection');
 await p.setViewportSize({width:390,height:844});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.ok(await p.locator('#gemini-preview').evaluate(n=>n.getBoundingClientRect().width<=390));await p.screenshot({path:process.env.HANDOFF_SCREENSHOT || 'gemini-handoff-mobile.png'});passed.push('mobile modal');assert.equal(calls,0);assert.deepEqual(errors,[]);passed.push('zero AI network calls with saved old endpoint; no page errors');
 console.log(JSON.stringify({passed,errors,aiRequests:calls},null,2));
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
